version: '3'

services:
  app:
    build: .
    container_name: managero-app
    entrypoint: .docker/entrypoint.sh
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres
    container_name: managero-db
    ports:
      - 5432:5432
    restart: always
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: managero
      POSTGRES_PASSWORD: managero123
      POSTGRES_DB: managero

  pgadmin:
    container_name: managero-db-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    links:
      - 'db:pgsql-server'
